import path from "path";

export interface RawPage {
  page_number: number;
  text: string;
}

/**
 * Uses pdfjs-dist directly rather than the `pdf-parse` wrapper the guide
 * lists as the first option. During development, `pdf-parse` (which bundles
 * a ~2018-era pdfjs-dist internally, last touched 2020) failed with "bad
 * XRef entry" on ordinary, valid PDFs generated by a current PDF library —
 * not a corrupted or unusual file, just a modern one. Since the brief
 * requires this to work on "any PDF... including ones never seen before,"
 * shipping on top of a parser demonstrated to fail on ordinary output wasn't
 * an acceptable trade for saving one dependency. pdfjs-dist is what `pdf-parse`
 * wraps in the first place and is actively maintained by Mozilla, so this
 * goes straight to it. See README "Limitations and Next Steps" for the
 * write-up of this finding.
 *
 * pdfjs-dist v4 ships ESM-only, hence the dynamic import from this CommonJS
 * module — `require()` cannot load an ESM package, but Node's dynamic
 * `import()` can, even from a CJS caller.
 */
async function loadPdfjs() {
  return import("pdfjs-dist/legacy/build/pdf.mjs");
}

// Bundled inside the pdfjs-dist package; pointing at it explicitly avoids a
// warning per document. Note: the Node-side font-data factory expects a
// plain filesystem path (with trailing separator), NOT a file:// URL —
// passing a file:// URL here silently fails to load glyph metrics (a
// UnknownErrorException warning, non-fatal to text extraction, but noisy).
const STANDARD_FONT_DATA_URL =
  path.join(require.resolve("pdfjs-dist/package.json"), "..", "standard_fonts") + path.sep;

/**
 * pdf.js splits a page's text into many small "items" along internal
 * glyph/font-run boundaries, not word boundaries. Naively joining every
 * item with a literal space (the previous implementation) inserts a space
 * between items even when there was no real gap on the page, which
 * fragments numbers and words that happen to cross a run boundary — e.g.
 * "82,152,503" arriving as three items ("82,15", "2", ",503") becomes
 * "82,15 2 ,503". This is more likely on PDFs with irregular embedded
 * fonts (see the "TT: undefined function: 32" warning pdf.js logs for this
 * document — a defect in the embedded TrueType font's glyph program, which
 * correlates with pdf.js producing more/odder item-boundary splits).
 *
 * Fix: only insert a space between two same-line items when there's an
 * actual horizontal gap between them (item N's rendered end position vs.
 * item N+1's start position), scaled relative to the current font size so
 * it works across different text sizes on the page. Items on a different
 * line always get a separating space (never a false concatenation across
 * lines). Item width is provided by pdf.js in unscaled text-space units,
 * consistent with the x-position in `transform[4]`.
 */
function joinTextItems(items: any[]): string {
  let text = "";
  let prevItem: any = null;

  for (const item of items) {
    if (!("str" in item) || item.str === "") continue;

    if (prevItem) {
      const sameLine = Math.abs(item.transform[5] - prevItem.transform[5]) < 1;
      if (sameLine) {
        const prevEndX = prevItem.transform[4] + (prevItem.width ?? 0);
        const gap = item.transform[4] - prevEndX;
        // Threshold relative to font size: a genuine word-boundary gap is
        // comparable to (or larger than) the glyph height; an artifact
        // split from a fragmented font run has a near-zero or negative gap.
        const fontSize = Math.abs(item.transform[3]) || 10;
        if (gap > fontSize * 0.15) {
          text += " ";
        }
      } else {
        text += " ";
      }
    }

    text += item.str;
    prevItem = item;
  }

  return text;
}

export async function extractPdfPages(buffer: Buffer): Promise<RawPage[]> {
  const pdfjsLib = await loadPdfjs();
  const data = new Uint8Array(buffer);

  const loadingTask = pdfjsLib.getDocument({
    data,
    standardFontDataUrl: STANDARD_FONT_DATA_URL,
  });

  const pdf = await loadingTask.promise;
  const pages: RawPage[] = [];

  try {
    for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber++) {
      const page = await pdf.getPage(pageNumber);
      try {
        const textContent = await page.getTextContent();
        const text = joinTextItems(textContent.items).replace(/\s+/g, " ").trim();
        pages.push({ page_number: pageNumber, text });
      } finally {
        page.cleanup();
      }
    }
  } finally {
    await pdf.destroy();
  }

  return pages;
}